# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: pre-release

on:
  push:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [amd64, 386, arm, arm64]
        os: [windows, linux, darwin]
        include:
          - ext: .exe
            os: windows
          - ext: ""
            os: linux
          - ext: ""
            os: darwin
    steps:
    - uses: actions/checkout@v3
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Build windows ${{ matrix.arch }}
      run: GOOS=windows GOARCH=${{ matrix.arch }} go build -o bin/smartmeter-bridge-${{ matrix.os }}-${{ matrix.arch }}${{ matrix.ext }} -v ./...
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.1.1
      with:
        path: bin/*

  pre-release:
    runs-on: ubuntu-latest
    needs: [test, build]
    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3.0.1
    - name: Automatic prerelease
      uses: marvinpinto/action-automatic-releases@v1.2.1
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        automatic_release_tag: "latest"
        prerelease: true
        title: Development build
        files: |
          artifact/*


